server:
  port: 8083

spring:
  application:
    name: auth.server
  r2dbc:
    url: r2dbc:mariadb://localhost:3309/auth_server?useUnicode=true&characterEncoding=utf8
    username: root
    password: admin123
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      springframework:
        r2dbc:
          core:
            DefaultDatabaseClient: debug
jwt:
  secret-key: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  access-token-expiration-time: 3600000
  refresh-token-expiration-time: 604800000